FROM python:3.10
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ .
COPY db/ /app/db/  
COPY frontend/ /app/frontend/
ENV PYTHONPATH=/app
CMD ["python", "server.py"]
