version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=8105274983:AAHgLSoRh1LLEy5vA_2WsPGpTDLLau7shs0
      - BACKEND_URL=https://fedf-194-44-82-106.ngrok-free.app/
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
